### ISSUE TITLE
Mouseover event does not work on geoJSON lines after installing leaflet-streetlabels

### ISSUE THREAD

**Issue by Matje1979** [triedeti/Leaflet.streetlabels#11]
Hello, 

I have installed leaflet-streetlabels and it works great, except that the mouse events that were previously working don't work anymore. When I hover over streets marked by geoJSON lines, nothing happens. It seems impossible to set the cursor to pointer when hovering over those lines. On the other hand, when I hover over pins, everything works as before. By inspecting the web page I noticed that the 'path' tags that represented geoJSON lines have disappeared from the html and are replaced by 'canvas' tags, and that tags that represent pins are still there. I also noticed that when I delete 'renderer : streetLabelsRenderer' from the code mouse events start working again. How can this problem be fixed?

Here is my code:

` <script>
    var streetLabelsRenderer = new L.StreetLabels({
      collisionFlg : true,
      propertyName : 'name',
      showLabelIf: function(layer) {
        return true; //layer.properties.type == "primary";
      },
      fontStyle: {
        dynamicFontSize: false,
        fontSize: 12,
        fontSizeUnit: "px",
        lineWidth: 6.0,
        fillStyle: "black",
        strokeStyle: "white",
      },
    });

var geojson6 =  {"type": "FeatureCollection","features": [{"type": "Feature","properties": {"name":"Petrakijina"},"geometry": {"type": "LineString","coordinates": [[18.424646258354187,43.860395155979084],[18.424606025218964,43.860387420163335],[18.424662351608276,43.860395155979084],[18.424667716026306,43.86039805690976],[18.424673080444336,43.86040095784028],[18.42457115650177,43.86037968434653],[18.4241433,43.8603084],[18.4238952,43.8602654],[18.42345,43.8602493],[18.4232477,43.860242],[18.4229471,43.8602312],[18.4229471,43.8602312],[18.4229127,43.8603619],[18.4228033,43.8607764],[18.422771394252777,43.860884444287336]]}}]};

var map =  L.map('map', {
        renderer : streetLabelsRenderer,
        preferCanvas: false
        // layers: [baseLayer, geo6]
    }).setView([43.8622, 18.4231], 16);

    L.tileLayer('https://{s}.tile.jawg.io/jawg-light/{z}/{x}/{y}{r}.png?access-token=lGN0EXNLjilOP6RW67TT7e0uo6ZEBlyQe2xiVsaqGogzdK7pQ5JJfr9XgeOlsc56', {
    	attribution: 'Tiles &copy; Esri &mdash; Esri, DeLorme, NAVTEQ, TomTom, Intermap, iPC, USGS, FAO, NPS, NRCAN, GeoBase, Kadaster NL, Ordnance Survey, Esri Japan, METI, Esri China (Hong Kong), and the GIS User Community'
    }).addTo(map);

var geo6 = L.geoJSON(geojson6, {
                    style: function(feature){
                        return {
                            weight: 8,
                            opacity: 1,
                            color: '#ffff00'
                        }
                    }
                }).addTo(map);

geo6.on('mouseover', function(){
            alert("Ovo radi");
            geo6.setStyle({
                color: 'red',
                opacity: 0.8
                cursor: 'pointer'
            });
        });

        geo6.on('mouseout', function(){
            geo6.setStyle({
                // color: 'rgb(51, 136, 255)',
                opacity: 1,
            });
        });

        geo6.on('click', function(e){
            // alert('You clicked the Petrakijina street.');
            var popup = L.popup().setContent(`This is the Petrakijina street`);
            popup.setLatLng(e.latlng).openOn(map);
        });`
</script>

So, the 'click' event works, but mouseover, and mouseout events are somehow not recognized. 
I would be grateful if you would explain to me what is going on here and help me solve the problem.

Cheers,
Damir

**Comment by leoneljdias** [comment]
Thanks for your comment.

It was a problem in L.LabelTextCollision.js.

Please use new version of Leaflet.streetlabels.js (v1.0.4) and you should now be able to use mouse events. 

See "console.log" in our demo page: https://triedeti.github.io/Leaflet.streetlabels/

Greetings!
