### ISSUE TITLE
Cannot change cursor style from grab to pointer 

### ISSUE THREAD

**Issue by Matje1979** [triedeti/Leaflet.streetlabels#12]
Hello,

I have a problem to make cursor change style when a user hovers over the streets with labels. 

Here is what I tried:
(geo6 is a geoJSON line with a streetlabel)

In my html file:

`1)  geo6.on('mouseover', function(){
            geo6.setStyle({
                cursor: 'pointer'
            });
        });

2)  geo6.on('mouseover', function(e){
            geo6.css('cursor', 'pointer !important');
        });

3) $('.leaflet-interactive).css('cursor', 'pointer')

    and

    $('.leaflet-interactive).css('cursor', 'pointer !important')

In my css file:

1) .leaflet-zoom-animated:hover{ cursor: pointer; }

2) .leaflet-interactive{
          cursor: pointer; 
}`

You can see my code in action here:  http://matje1979.pythonanywhere.com/

I hope you can help me solve this problem. 

Greetings!

Damir

**Comment by leoneljdias** [comment]
Thanks for your comment.

Please update to the new version Leaflet.streetlabels.js (v1.0.5).

Greetings!
