### ISSUE TITLE
Sticking out corners of stroked text

### ISSUE THREAD

**Issue by lobovmaxim** [triedeti/Leaflet.streetlabels#17]
I use option strokeStyle: "white" and lineWidth: 1.0 to make the labels more visible on the map, but here is a problem with sticking out corners 
![screenshot](https://user-images.githubusercontent.com/14214016/167558779-b485d268-9832-4ffb-9e6b-2c983c48996e.jpg)

I think It would be better use ctx.lineJoin="round";

You can add it on the line 168 after this lines:
ctx.fillStyle = this.options.fontStyle.fillStyle;
ctx.strokeStyle = this.options.fontStyle.strokeStyle;

**Comment by jdsantos** [comment]
Hi @lobovmaxim !
thanks for your input. Can you fork the repo, and this line and make a PR please?
