### ISSUE TITLE
How does streelabel.js works

### ISSUE THREAD

**Issue by 8dgeSolution** [triedeti/Leaflet.streetlabels#18]
Hi All, 
Does this js logic actually know the street labels ?? (i.e. does it do a reverse geo coding etc)?

**Comment by jdsantos** [comment]
Hi @8dgeSolution,

streetlabels does not do any reverse geo coding. It only displays labels along polylines, following polyline contours. For reverse geocoding checkout the leaflet plugin Esri Leaflet (Esri/esri-leaflet)
