### ISSUE TITLE
Label upside down

### ISSUE THREAD

**Issue by lmdc45** [triedeti/Leaflet.streetlabels#3]
Hi,

Is there a simple way to have the label always from a left to right direction?
![Capture](https://user-images.githubusercontent.com/47163513/72492281-b86f0e80-3870-11ea-9a39-54c7cc2c6055.PNG)

At this stage depending on feature line direction it can be flipped over.

Thanks

Louis

**Comment by jdsantos** [comment]
Hi Louis, 

Thanks for the issue report! Now there is no simple trick  i can give  you so that it gets drawn correctly. However, we make this issue a priority and try to fix it asap.

Thanks,

Jorge

**Comment by lmdc45** [comment]
Thanks

**Comment by yfreemark** [comment]
Has this issue been addressed? I see that this issue was closed, but I'm not sure how to implement a change if there has been one. Thanks!
