### ISSUE TITLE
Two labels on polygon

### ISSUE THREAD

**Issue by lobovmaxim** [triedeti/Leaflet.streetlabels#8]
There are appears two labels on polygon because of L.Polygon inherit from L.Polyline. So, layer instanceof L.Polygon - is true and layer instanceof L.Polyline - is true

See  on lines 116-121:
if (layer instanceof L.Polygon || layer instanceof L.CircleMarker) {
    // Draw label for Polygon
}
if(layer instanceof L.Polyline){
    // Draw label for Polyline
}

Please, correct as:
if (layer instanceof L.Polygon || layer instanceof L.CircleMarker) {
    // Draw label for Polygon
}else if(layer instanceof L.Polyline){
    // Draw label for Polyline
}

**Comment by leoneljdias** [comment]
Hi @lobovmaxim 

Thanks for the issue report! We make this issue a priority and try to fix it asap.

Thanks,
Leo
